<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-algaher0805/blob/main/m%C3%B3dulo_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

El módulo 5 comienza mostrando un array en numpy(numpy es una libreria de python usada para trabajar con arrays y matrices), el cuál es similar a una lista, y al igual que en una lista, se puede acceder a cada uno de sus elementos mediante un indíce

In [1]:
#la abreviación estandar para numpy es np
import numpy as np
x=np.array([4,5,6,7,8,12])
print(x[0])
print(x[4])

4
8


In [2]:
#si obtenemos el tipo de datos de x obtenemos
type(x)

numpy.ndarray

In [4]:
#Esto era obvio porque nosotros lo creamos pero si este no hubiera sido el caso esta función es útil,  
#también, si queremos saber el tipo de datos que contiene este arreglo utilizamos la siguiente función:
x.dtype


dtype('int64')

In [5]:
#podemos obtener algunos datos interesantes acerca del tamaño y dimenciones del arreglo con las siguientes funciones
print(x.size)
print(x.ndim)
print(x.shape)

6
1
(6,)


In [7]:
#para sustituir alguno de los valores del arreglo simplemente hacemos referencia al elemento mediante el # de índice y asignamos el nuevo valor
x[5]=0
x

array([4, 5, 6, 7, 8, 0])

In [9]:
#para obtener subconjuntos del arreglo:
y=x[1:3]
y
#al iguan que en las listas, el nuevo subconjunto contendrá los elementos entre el primero y hasta el numero previo al segundo específicado en los parámetros,
#en este caso, se observa que el subconjunto consta de los elementos 1 y 2 del conjunto original.

array([5, 6])

Una ventaja de la libreria numpy es que generalme realiza más rápido algunas de las operaciones que con las funciones normales de python, además que también necesitan menos memoria. 

In [11]:
#Una de estas operaciones es la suma y resta de dos vectores
x=np.array([9,1])
y=np.array([2,6])
z=x+y
print(z)
w=x-y
print(w)


[11  7]
[ 7 -5]


In [13]:
#También se puede multiplicar los vectores por un escalar
z=3*x
z

array([27,  3])

In [14]:
#se puede multiplicar las entradas de dos vectores
z=x*y
print(z)
#o se puede obtener el producto punto
w=np.dot(x,y)
print(w)

[18  6]
24


Otro de los conceptos que se introducen en el curso es el de las funciones universales, las cuales se refieren a las funciones que se pueden aplicar a los arreglos de numpy.

In [17]:
#algunas funciones universales son:
a=x.mean()
b=x.max()
print(a)
print(b)


5.0
9


In [21]:
#otra función útil de numpy es linspace que devuelve un conjunto de x datos (x es el tercer agumento de la función), 
# entre los números ingresados como argumentos 
a=np.linspace(0,10,num=4)
a

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [23]:
np.dot(np.array([1,-1]),np.array([1,1]))

0