<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-algaher0805/blob/main/m%C3%B3dulo_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

El módulo 5 comienza mostrando un array en numpy(numpy es una libreria de python usada para trabajar con arrays y matrices), el cuál es similar a una lista, y al igual que en una lista, se puede acceder a cada uno de sus elementos mediante un indíce

In [2]:
#la abreviación estandar para numpy es np
import numpy as np
x=np.array([4,5,6,7,8,12])
print(x[0])
print(x[4])

4
8


In [ ]:
#si obtenemos el tipo de datos de x obtenemos
type(x)

numpy.ndarray

In [ ]:
#Esto era obvio porque nosotros lo creamos pero si este no hubiera sido el caso esta función es útil,  
#también, si queremos saber el tipo de datos que contiene este arreglo utilizamos la siguiente función:
x.dtype


dtype('int64')

In [ ]:
#podemos obtener algunos datos interesantes acerca del tamaño y dimensiones del arreglo con las siguientes funciones
print(x.size)
print(x.ndim)
print(x.shape)

6
1
(6,)


In [ ]:
#para sustituir alguno de los valores del arreglo simplemente hacemos referencia al elemento mediante el # de índice y asignamos el nuevo valor
x[5]=0
x

array([4, 5, 6, 7, 8, 0])

In [ ]:
#para obtener subconjuntos del arreglo:
y=x[1:3]
y
#al iguan que en las listas, el nuevo subconjunto contendrá los elementos entre el primero y hasta el numero previo al segundo específicado en los parámetros,
#en este caso, se observa que el subconjunto consta de los elementos 1 y 2 del conjunto original.

array([5, 6])

Una ventaja de la libreria numpy es que generalme realiza más rápido algunas de las operaciones que con las funciones normales de python, además que también necesitan menos memoria. 

In [ ]:
#Una de estas operaciones es la suma y resta de dos vectores
x=np.array([9,1])
y=np.array([2,6])
z=x+y
print(z)
w=x-y
print(w)


[11  7]
[ 7 -5]


In [ ]:
#También se puede multiplicar los vectores por un escalar
z=3*x
z

array([27,  3])

In [ ]:
#se puede multiplicar las entradas de dos vectores
z=x*y
print(z)
#o se puede obtener el producto punto
w=np.dot(x,y)
print(w)

[18  6]
24


Otro de los conceptos que se introducen en el curso es el de las funciones universales, las cuales se refieren a las funciones que se pueden aplicar a los arreglos de numpy.

In [ ]:
#algunas funciones universales son:
a=x.mean()
b=x.max()
print(a)
print(b)


5.0
9


In [ ]:
#otra función útil de numpy es linspace que devuelve un conjunto de x datos (x es el tercer agumento de la función), 
# entre los números ingresados como argumentos 
a=np.linspace(0,10,num=4)
a

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [ ]:
np.dot(np.array([1,-1]),np.array([1,1]))

0

En ester módulo también se muestra como crear arreglos 2D con numpy

In [ ]:
#el siguiente código crea un arreglo en 2 domenciones
x=[[5,6,7],[1,5,90],[2,4,0]]
x=np.array(x)
x

array([[ 5,  6,  7],
       [ 1,  5, 90],
       [ 2,  4,  0]])

In [ ]:
#podemos obtener la dimensión y el tamaño del arreglo de la sguiente manera
print(x.ndim)
print(x.size)

2
9


In [ ]:
#al igual que los arreglos de una dimensión, se puede acceder a cualquier elemento del arreglo de la siguiente manera:
x[1,2]
#el primer índice se refiere al renglón y el segundo índice a la columna

90

In [ ]:
#para obtener subconjuntos del arreglo se utilizan los índices de la siguiente manera
x[2,1:3]
#aquí obtenemos los registros 2 y 3 del último renglón

array([4, 0])

In [ ]:
#o podemos obtener la segunda columna completa
print(x[0:3,1])
#o bien
print(x[:,1])

[6 5 4]
[6 5 4]


In [ ]:
#los arreglos de dos dimensiones pueden sumarse, restarse o multiplicarse por un escalar al igual que una matriz

y=np.array([[1,3,4],[2,0,6],[12,3,3]])
print(y)
print(x+y)
print(3*x)

[[ 1  3  4]
 [ 2  0  6]
 [12  3  3]]
[[ 6  9 11]
 [ 3  5 96]
 [14  7  3]]
[[ 15  18  21]
 [  3  15 270]
 [  6  12   0]]


In [ ]:
#también se pueden multiplicar los arreglos entrada a entrada
x*y

array([[  5,  18,  28],
       [  2,   0, 540],
       [ 24,  12,   0]])

In [3]:
#También se puede hacer multiplicación de dos arreglos como si fuera multiplicación matricial de la siguiente manera

x=np.array([[1,2,3],[7,8,9]])
y=np.array([[2,3],[3,4],[7,3]])
z=np.dot(x,y)
z

array([[ 29,  20],
       [101,  80]])